name: Docker publish rootless

on:
  workflow_dispatch:
    inputs:
      push_to_dockerhub:
        description: 'Push the image to Docker Hub in addition to GHCR.'
        type: boolean
        default: true
      custom_tag:
        description: 'Optional additional tag to publish (e.g. v1.2.3).'
        required: false
        default: ''

permissions:
  contents: read        # Access to repository contents
  packages: write       # Write access for pushing to GHCR
  id-token: write       # Required for OIDC authentication (if used)
  attestations: write   # Required for signing and attestation (if needed)

env:
  DOCKERHUB_REPO: sysadminsmedia/homebox
  GHCR_REPO: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    env:
      PUSH_TO_DOCKERHUB: ${{ fromJson(toJson(inputs.push_to_dockerhub)) ? 'true' : 'false' }}
      CUSTOM_TAG: ${{ inputs.custom_tag }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7

    steps:
      - name: Enable Debug Logs
        run: echo "##[debug]Enabling debug logging"
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          set -euo pipefail
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          branch=${{ github.event.pull_request.number || github.ref_name }}
          echo "BRANCH=${branch//\//-}" >> $GITHUB_ENV
          dockernames="${{ env.GHCR_REPO }}"
          if [ "${{ env.PUSH_TO_DOCKERHUB }}" = "true" ]; then
            dockernames="${dockernames},${{ env.DOCKERHUB_REPO }}"
          fi
          echo "DOCKERNAMES=$dockernames" >> $GITHUB_ENV
          version='${{ github.ref_name }}'
          if [ -n "${{ env.CUSTOM_TAG }}" ]; then
            version='${{ env.CUSTOM_TAG }}'
          fi
          echo "VERSION_ARG=$version" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ env.DOCKERHUB_REPO }},enable=${{ env.PUSH_TO_DOCKERHUB == 'true' }}
            name=${{ env.GHCR_REPO }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: env.PUSH_TO_DOCKERHUB == 'true'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: ghcr.io/amitie10g/binfmt:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=ghcr.io/amitie10g/buildkit:master

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: . # Explicitly specify the build context
          file: ./Dockerfile.rootless # Explicitly specify the Dockerfile
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,"name=${{ env.DOCKERNAMES }}",push-by-digest=true,name-canonical=true,push=${{ github.event_name != 'pull_request' }}
          cache-from: type=registry,ref=ghcr.io/sysadminsmedia/devcache:${{ env.PLATFORM_PAIR }}-${{ env.BRANCH }}-rootless
          cache-to: type=registry,ref=ghcr.io/sysadminsmedia/devcache:${{ env.PLATFORM_PAIR }}-${{ env.BRANCH }}-rootless,mode=max,ignore-error=true
          build-args: |
            VERSION=${{ env.VERSION_ARG }}
            COMMIT=${{ github.sha }}
          provenance: true
          sbom: true
          annotations: ${{ steps.meta.outputs.annotations }}
          
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    needs:
      - build
    env:
      PUSH_TO_DOCKERHUB: ${{ fromJson(toJson(inputs.push_to_dockerhub)) ? 'true' : 'false' }}
      CUSTOM_TAG: ${{ inputs.custom_tag }}

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: env.PUSH_TO_DOCKERHUB == 'true'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=ghcr.io/amitie10g/buildkit:master

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ env.DOCKERHUB_REPO }},enable=${{ env.PUSH_TO_DOCKERHUB == 'true' }}
            name=${{ env.GHCR_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=schedule,pattern=nightly
            type=raw,value=${{ env.CUSTOM_TAG }},enable=${{ env.CUSTOM_TAG != '' }}
          flavor: |
            suffix=-rootless,onlatest=true

      - name: Create manifest list and push GHCR
        id: push-ghcr
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.GHCR_REPO }}@sha256:%s ' *)

      - name: Create manifest list and push Dockerhub
        id: push-dockerhub
        working-directory: /tmp/digests
        if: env.PUSH_TO_DOCKERHUB == 'true'
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKERHUB_REPO }}@sha256:%s ' *)
